# Generated by Django 4.1.1 on 2022-10-17 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0002_room_timeslot_alter_onetimetoken_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimetoken',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 1, 57, 28, 596540)),
        ),
        migrations.RemoveField(
            model_name='techsession',
            name='room',
        ),
        migrations.AlterField(
            model_name='techsession',
            name='session_type',
            field=models.CharField(choices=[('Keynote', 'Keynote'), ('Sponsor', 'Sponsor'), ('Tech', 'Tech'), ('Community', 'Community'), ('Online', 'Online'), ('TimeTable', 'TimeTable')], default='Tech', max_length=20),
        ),
        migrations.RemoveField(
            model_name='techsession',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='techsession',
            name='room',
            field=models.ManyToManyField(blank=True, to='openinfradays.room'),
        ),
        migrations.AddField(
            model_name='techsession',
            name='time_slot',
            field=models.ManyToManyField(blank=True, to='openinfradays.timeslot'),
        ),
    ]
