# Generated by Django 4.1.1 on 2022-10-17 02:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openinfradays', '0004_alter_onetimetoken_expire_at_remove_techsession_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimetoken',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 2, 33, 15, 921562)),
        ),
        migrations.AlterField(
            model_name='techsession',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='openinfradays.speaker'),
        ),
    ]
